apiVersion: v1
kind: ServiceAccount
{{- with .Values.global.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{- end }}
metadata:
  name: randoli-sre-agent
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "selectorLabels" . | nindent 4 }}
    {{- include "labels" . | nindent 4 }}
