apiVersion: v1
kind: ServiceAccount
metadata:
  name: randoli-sre-agent
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "selectorLabels" . | nindent 4 }}
    {{- include "labels" . | nindent 4 }}
